---
apiVersion: v1
kind: Namespace
metadata:
  name: namespaceName
___
apiVersion: v1
kind: ResourceQuota
metadata:
  name: namespaceName-resources
spec:
  hard:
    pods: "5"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "5"
    limits.memory: 5Gi
